export const LOADING = 'LOADING'
export const ERROR = 'ERROR'
export const RESET =  "RESET"
export const GETSUCCESS = 'GETSUCCESS'

export const LOGINSUCCESS = "LOGINSUCCESS";
export const REGISTERSUCCESS = "REGISTERSUCCESS";
export const ACCOUNT_UPDATED = "ACCOUNT_UPDATED";
export const ACCOUNT_DELETED ="ACCOUNT_DELETED";