export const LOADING = 'LOADING'
export const ERROR = 'ERROR'
export const RESET_AUTH =  "RESET_AUTH"
export const RESET_JOBSEEKER = "RESET_JOBSEEKER"
export const RESET_RECRUITER = "RESET_RECRUITER"
export const RESETALL = "RESETALL"
export const GETSUCCESS = 'GETSUCCESS'
export const RESETMSG = "RESETMSG";

export const LOGINSUCCESS = "LOGINSUCCESS";
export const REGISTERSUCCESS = "REGISTERSUCCESS";
export const ACCOUNT_UPDATED = "ACCOUNT_UPDATED";
export const ACCOUNT_DELETED ="ACCOUNT_DELETED";

export const JOB_POSTED = 'JOB_POSTED';
export const JOB_GETTED = "JOB_GETTED";
export const JOB_DELETED = "JOB_DELETED";
export const JOB_UPDATED = "JOB_UPDATED";

export const APPLICATION_GETTED = "APPLICATION_GETTED";
export const APPLICATION_UPDATED = "APPLICATION_UPDATED";
export const APPLIED = 'APPLIED';

export const ALL_JOBS_GETTED = "ALL_JOBS_GETTED";
export const JOB_APPLIED = "JOB_APPLIED";
export const APPLIED_JOB_APPLICATION = "APPLIED_JOB_APPLICATION";

export const GOT_AI_OUTPUT = "GOT_AI_OUTPUT";
export const GOT_AI_OUTPUT_RECRUITER = "GOT_AI_OUTPUT_RECRUITER";