export const LOADING = 'LOADING'
export const ERROR = 'ERROR'
export const RESET =  "RESET"
export const RESETALL = "RESETALL"
export const GETSUCCESS = 'GETSUCCESS'

export const LOGINSUCCESS = "LOGINSUCCESS";
export const REGISTERSUCCESS = "REGISTERSUCCESS";
export const ACCOUNT_UPDATED = "ACCOUNT_UPDATED";
export const ACCOUNT_DELETED ="ACCOUNT_DELETED";

export const JOB_POSTED = 'JOB_POSTED';
export const JOB_GETTED = "JOB_GETTED";
export const JOB_DELETED = "JOB_DELETED";
export const JOB_UPDATED = "JOB_UPDATED";

export const APPLICATION_GETTED = "APPLICATION_GETTED";
export const APPLICATION_UPDATED = "APPLICATION_UPDATED";
export const APPLIED = 'APPLIED';

export const ALL_JOBS_GETTED = "ALL_JOBS_GETTED";
export const JOB_APPLIED = "JOB_APPLIED";